name: Main Pipeline

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/workflows/Terraform-Create.yaml'
      - '.github/workflows/terraform-destroy.yml'
      - 'terraform/**'
      - '**.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'terraform/**'
      - '**.md'


jobs:

  
  trigger-ci:
    name: Trigger CI Workflow
    uses: ./.github/workflows/ci.yaml
    with:
      environment: dev 
    secrets: inherit


  trigger-cd:
    name: Trigger CD Workflow
    needs: trigger-ci
    uses: ./.github/workflows/cd.yaml
    with:
      environment: dev  
    secrets: inherit

  trigger-promotion:
    name: Trigger promotion
    needs: trigger-cd
    uses: ./.github/workflows/systemtests.yml
    with:
      environment: dev  
    secrets: inherit